WebMVC/Controllers/PublisherController.cs
using System.Net.Http.Headers;
using System.Text;
using System.Text.Json;
using Entities.Dtos;
using Entities.RequestModels;
using Microsoft.AspNetCore.Mvc;

namespace WebMVC.Controllers;

public class PublisherController : Controller
{
    private readonly HttpClient client = null;

    private string apiUrl = "";

    public PublisherController()
    {
        client = new HttpClient();
        var contentType = new MediaTypeWithQualityHeaderValue("application/json");
        client.DefaultRequestHeaders.Accept.Add(contentType);
        apiUrl = "https://localhost:7125/Publisher";
    }
    
    
    public async Task<IActionResult> Index()
    {
        var getAllUrl = apiUrl + "/Get";
        var response = await client.GetAsync(getAllUrl);
        var strData = await response.Content.ReadAsStringAsync();
        var options = new JsonSerializerOptions()
        {
            PropertyNameCaseInsensitive = true
        };
        var listPublisher = JsonSerializer.Deserialize<List<PublisherDto>>(strData, options);
        return View(listPublisher);
    }
    
    [HttpPost]
    public async Task<IActionResult> Index(int? pubId, string? publisherName, string? city)
    {
        if (pubId == null && string.IsNullOrEmpty(publisherName) && string.IsNullOrEmpty(city))
            return RedirectToAction("Index");
        var filterUrl = "https://localhost:7125/Publisher/Get?$filter=";
        var firstFilter = true;
        if (pubId != null)
        {
            filterUrl += "PubId eq " + pubId;
            firstFilter = false;
            ViewBag.PubId = pubId;
        }

        if (publisherName != null)
        {
            if (!firstFilter) filterUrl += " and ";
            else firstFilter = false;
            filterUrl += "contains(publishername, '" + publisherName + "')";
            ViewBag.PublisherName = publisherName;
        }
        
        if (city != null)
        {
            if (!firstFilter) filterUrl += " and ";
            else firstFilter = false;
            filterUrl += "contains(city, '" + city + "')";
            ViewBag.City = city;
        }
        
        var response = await client.GetAsync(filterUrl);
        var strData = await response.Content.ReadAsStringAsync();
        var options = new JsonSerializerOptions()
        {
            PropertyNameCaseInsensitive = true
        };
        var listProduct = JsonSerializer.Deserialize<List<PublisherDto>>(strData, options);
        return View(listProduct);
    }

    [HttpGet]
    public IActionResult Create(int? id)
    {
        var addPublisherRequest = new AddPublisherRequest();
        return View(addPublisherRequest);
    }

    [HttpPost]
    public async Task<IActionResult> Create(AddPublisherRequest request)
    {
        if (ModelState.IsValid)
        {
            var getAllUrl = apiUrl + "/Add";
            var jsonContent = new StringContent(JsonSerializer.Serialize(request), Encoding.UTF8, "application/json");
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", Request.Cookies["jwt"]);
            var response = await client.PostAsync(getAllUrl, jsonContent);
            var strData = await response.Content.ReadAsStringAsync();
            var options = new JsonSerializerOptions()
            {
                PropertyNameCaseInsensitive = true
            };
            var publisherDto = JsonSerializer.Deserialize<PublisherDto>(strData, options);
            TempData["success"] = "Publisher with id = " + publisherDto.PubId + " is Created done!";
            
        }

        return RedirectToAction("Index");
    }

    [HttpGet]
    public async Task<IActionResult> Update(int? id)
    {
        var publisherDto = new PublisherDto();
        var getAllUrl = apiUrl + "/Get/" + id;
        var response = await client.GetAsync(getAllUrl);
        var strData = await response.Content.ReadAsStringAsync();
        var options = new JsonSerializerOptions()
        {
            PropertyNameCaseInsensitive = true
        };
        publisherDto = JsonSerializer.Deserialize<PublisherDto>(strData, options);
        return View(publisherDto);
    }

    [HttpPost]
    public async Task<IActionResult> Update(PublisherDto request)
    {
        if (ModelState.IsValid)
        {
            var getAllUrl = apiUrl + "/Update";
            var jsonContent = new StringContent(JsonSerializer.Serialize(request), Encoding.UTF8, "application/json");
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", Request.Cookies["jwt"]);
            Console.WriteLine(JsonSerializer.Serialize(request));
            var response = await client.PostAsync(getAllUrl, jsonContent);
            var strData = await response.Content.ReadAsStringAsync();
            var options = new JsonSerializerOptions()
            {
                PropertyNameCaseInsensitive = true
            };
            var publisherDto = JsonSerializer.Deserialize<PublisherDto>(strData, options);
            TempData["success"] = "Publisher with id = " + publisherDto.PubId + " is Updated done!";
        }
        return RedirectToAction("Index");
    }
}

WebMVC/Views/Publisher/Create.cshtml
@model Entities.RequestModels.AddPublisherRequest

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Create Publisher</h2>
<form method="post" asp-action="Create">
    <div class="border p-3 mt-4">
        <div class="row pb-3">
            <h2 class="text-primary">Create Publisher</h2>
            <hr/>
        </div>
        <div asp-validation-summary="All"></div>
        <div class="row mb-3">
            <label asp-for="PublisherName"></label>
            <input asp-for="PublisherName" class="form-control"/>
            <span asp-validation-for="PublisherName" class="text-danger"></span>
        </div>
        <div class="row mb-3">
            <label asp-for="City"></label>
            <input asp-for="City" class="form-control"/>
            <span asp-validation-for="City" class="text-danger"></span>
        </div>
        <div class="row mb-3">
            <label asp-for="State"></label>
            <input asp-for="State" class="form-control"/>
            <span asp-validation-for="State" class="text-danger"></span>
        </div>
        <div class="row mb-3">
            <label asp-for="Country"></label>
            <input asp-for="Country" class="form-control"/>
            <span asp-validation-for="Country" class="text-danger"></span>
        </div>
        

        <button class="btn btn-primary" type="submit">Create</button>


    </div>
    <a asp-action="Index" asp-controller="Publisher">Back to list</a>
</form>

WebMVC/Views/Publisher/Index.cshtml
@model List<Entities.Dtos.PublisherDto>

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Publisher List</h2>
<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
    <tr>
        <th>
            PubId
        </th>
        <th>
            Publisher Name
        </th>
        <th>
            City
        </th>
        <th>
            
        </th>
        


    </tr>
    </thead>

    <tbody>
    <tr>
        <form method="post" asp-action="Index">
            <td> <input name="pubId" class="form-control" value="@ViewBag.PubId"/> </td>
            <td> <input name="publisherName" class="form-control" value="@ViewBag.PublisherName"/> </td>
            <td> <input name="city" class="form-control" value="@ViewBag.City"/> </td>
            <td> <input type="submit" class="btn-secondary" value="Search" /></td>
        </form>
    </tr>
    
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.PubId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PublisherName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>

            <td>
                @Html.ActionLink("Edit", "Update", new { id = item.PubId })
            </td>

        </tr>
    }
    </tbody>
</table>

WebMVC/Views/Publisher/Update.cshtml
@model Entities.Dtos.PublisherDto

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Update Publisher</h2>
<form method="post" asp-action="Update">
    <div class="border p-3 mt-4">
        <div class="row pb-3">
            <h2 class="text-primary">Update Publisher</h2>
            <hr/>
        </div>
        <div asp-validation-summary="All"></div>
        <input asp-for="PubId" value="@Model.PubId" type="hidden"/>
        <div class="row mb-3">
            <label asp-for="PublisherName"></label>
            <input asp-for="PublisherName" class="form-control" value="@Model.PublisherName"/>
            <span asp-validation-for="PublisherName" class="text-danger"></span>
        </div>
        <div class="row mb-3">
            <label asp-for="City"></label>
            <input asp-for="City" class="form-control" value="@Model.City"/>
            <span asp-validation-for="City" class="text-danger"></span>
        </div>
        <div class="row mb-3">
            <label asp-for="State"></label>
            <input asp-for="State" class="form-control" value="@Model.State"/>
            <span asp-validation-for="State" class="text-danger"></span>
        </div>
        <div class="row mb-3">
            <label asp-for="Country"></label>
            <input asp-for="Country" class="form-control" value="@Model.Country"/>
            <span asp-validation-for="Country" class="text-danger"></span>
        </div>

        <button class="btn btn-primary" type="submit">Update</button>


    </div>
    <a asp-action="Index" asp-controller="Publisher">Back to list</a>
</form>